services:
  sentinel:
    <<: &default-sentinel
      env_file:
        - deploy/local/sentinel.env
      restart: always
    build:
      context: sentinel
      dockerfile: Dockerfile
    command: ["./sentinel"]
    depends_on:
      - "sentinel_psql"
    ports:
      - "8080:8080"
      - "9090:9090"

  sentinel_psql:
    <<: *default-sentinel
    image: postgres:17-alpine
    ports:
      - "5454:5432"
    expose:
      - "5432"
    volumes:
      - ./data/sentinel_data:/var/lib/postgresql/data
