services:
  sentinel:
    build:
      context: sentinel
      dockerfile: Dockerfile
    command: ["./sentinel"]
    env_file:
      - deploy/local/auth.env
    depends_on:
      - "sentinel_psql"
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: always

  sentinel_psql:
    image: postgres:17-alpine
    restart: always
    env_file:
      - deploy/local/auth.env
    ports:
      - "5454:5432"
    expose:
      - "5432"
    volumes:
      - ./data/sentinel_data:/var/lib/postgresql/data
